version: '3.8'

services:
  digits_classifier:
    build: .
    volumes:
      - ./input_images:/usr/src/app/input_images
      - ./output_predictions:/usr/src/app/output_predictions
    command: python inference.py